-- ==============================================================================
-- INMOBILIARIA NORTE CHICO: MÓDULO DE BLOG, GUÍAS & ARTÍCULOS
-- Ejecutar este script en el SQL Editor de Supabase
-- ==============================================================================

-- 1. Crear tabla de Artículos
CREATE TABLE IF NOT EXISTS articulos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    categoria VARCHAR(100) NOT NULL DEFAULT 'Estrategia & Plusvalía',
    resumen TEXT NOT NULL,
    contenido JSONB DEFAULT '[]'::jsonb,
    puntos_clave JSONB DEFAULT '[]'::jsonb,
    autor VARCHAR(100) NOT NULL DEFAULT 'Equipo Norte Chico',
    autor_rol VARCHAR(100) NOT NULL DEFAULT 'Comité Editorial',
    imagen_url TEXT NOT NULL DEFAULT '/PR_CHANCAY_desktop.webp',
    tiempo_lectura VARCHAR(50) NOT NULL DEFAULT '4 min de lectura',
    destacado BOOLEAN NOT NULL DEFAULT false,
    publicado BOOLEAN NOT NULL DEFAULT true,
    badge_color VARCHAR(20) NOT NULL DEFAULT '#cb9f74',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Habilitar Seguridad por Filas (Row Level Security - RLS)
ALTER TABLE articulos ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acceso Cero-Fugas:
-- Lectura pública: cualquiera puede leer artículos publicados
CREATE POLICY "Lectura pública de artículos publicados" 
ON articulos FOR SELECT 
TO anon, authenticated 
USING (publicado = true);

-- Gestión administrativa: usuarios autenticados del CRM pueden ver, insertar, actualizar y eliminar
CREATE POLICY "Gestión total para administradores autenticados" 
ON articulos FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- 4. Inserción de Artículos Semilla Iniciales
INSERT INTO articulos (titulo, categoria, resumen, contenido, puntos_clave, autor, autor_rol, imagen_url, tiempo_lectura, destacado, publicado, badge_color)
VALUES 
(
    'Megapuerto de Chancay 2026: Por qué el Eje Chancay-Huaral liderará la plusvalía inmobiliaria',
    'Estrategia & Plusvalía',
    'Análisis de impacto macroeconómico, demanda de habilitación urbana y proyección de revalorización por metro cuadrado para inversionistas que buscan alta rentabilidad.',
    '[
        {"subtitle": "1. El Hub Portuario más moderno de Sudamérica", "text": "La consolidación operativa del Megapuerto Multipropósito de Chancay marca un hito histórico en el comercio marítimo bioceánico. La reducción del tiempo de tránsito de 35 a solo 10 días hacia Asia convierte al litoral del Norte Chico en el epicentro comercial y logístico indiscutible del Perú."},
        {"subtitle": "2. Efecto Multiplicador en Terrenos Residenciales y Comerciales", "text": "El desarrollo portuario no solo atrae almacenes y parques logísticos; genera una demanda exponencial de viviendas, residencias de campo para ejecutivos, zonas comerciales y servicios de hotelería y recreación en Chancay y los valles fértiles de Huaral."},
        {"subtitle": "3. La Regla de Oro: Comprar en Fase de Expansión", "text": "Quienes adquieren terrenos independizados hoy capturan el valor inicial antes de la maduración de los proyectos viales complementarios (vía periurbana y tren costero). El metro cuadrado en la zona mantiene una curva alcista sostenida."}
    ]'::jsonb,
    '["Conexión directa Chancay-Asia con reducción drástica de fletes.", "Alta demanda de suelo urbano para profesionales y ejecutivos del sector portuario.", "Excelente relación precio/m² con proyección de duplicación de valor en el mediano plazo."]'::jsonb,
    'Dirección Estratégica Norte Chico',
    'Comité de Inversiones',
    '/PR_CHANCAY_desktop.webp',
    '5 min de lectura',
    true,
    true,
    '#cb9f74'
),
(
    'Guía Legal SUNARP: Cómo verificar que un terreno en Chancay está 100% saneado',
    'Saneamiento Legal SUNARP',
    'Paso a paso para revisar partidas registrales, planos catastrales y evitar fraudes inmobiliarios. Compra con total certeza jurídica.',
    '[
        {"subtitle": "1. La Partida Electrónica Independizada", "text": "Nunca compre acciones y derechos indivisos sin un plano visado. Cada lote debe contar con su propia Partida Registral en SUNARP, donde figure el área exacta, linderos y titularidad única libre de embargos."},
        {"subtitle": "2. Certificado Catastral y Zonificación Municipal", "text": "Verifique que el lote cuente con zonificación residencial (RDM/RDA) o comercio compatible con los planes de desarrollo urbano aprobados por la Municipalidad de Chancay o Huaral."},
        {"subtitle": "3. El Protocolo Cero-Riesgos de Norte Chico", "text": "En nuestro catálogo, ninguna propiedad se publica como disponible sin previa auditoría notarial y registral completa, garantizando entrega de título y posesión inmediata."}
    ]'::jsonb,
    '["Exija siempre Certificado Registral Inmobiliario (CRI) actualizado.", "Verifique que no existan cargas, hipotecas ni litigios pendientes.", "Firma de Escritura Pública ante Notario con bancarización completa."]'::jsonb,
    'Área Legal & Saneamiento',
    'Operaciones SUNARP',
    '/PR_PLAZA_CHANCAY_desktop.webp',
    '4 min de lectura',
    false,
    true,
    '#10b981'
),
(
    '5 Pasos para adquirir tu lote residencial con Financiamiento Directo y sin bancos',
    'Guía de Compra & Ventas',
    'Desde la selección del metraje y recorrido guiado en campo, hasta la firma notarial y entrega física del terreno con hitos topográficos.',
    '[
        {"subtitle": "Paso 1: Asesoría y Selección de Ubicación", "text": "Defina su objetivo: vivienda familiar de campo, casa de retiro o inversión a mediano plazo para reventa. Le presentamos las opciones que mejor se adaptan a su presupuesto."},
        {"subtitle": "Paso 2: Recorrido Guiado en el Terreno", "text": "Coordinamos una visita presencial para inspeccionar la topografía, accesos, vistas panorámicas y la delimitación exacta de los hitos."},
        {"subtitle": "Paso 3: Separación y Plan de Pago", "text": "Separe su lote con un monto accesible y elija entre pago al contado con descuento especial o cuotas mensuales estructuradas a su medida."},
        {"subtitle": "Paso 4 y 5: Firma Notarial y Posesión", "text": "Formalización del contrato ante notario público colegiado y entrega inmediata de la posesión para que inicie su proyecto."}
    ]'::jsonb,
    '["Visita guiada sin costo con asesor personal.", "Flexibilidad de pagos en Dólares (USD) o Soles (PEN).", "Atención inmediata vía WhatsApp al +56 9 8281 6844."]'::jsonb,
    'Equipo Comercial & Conversión',
    'Ventas Norte Chico',
    '/PR_ECOTRULY_PARK_desktop.webp',
    '3 min de lectura',
    false,
    true,
    '#38bdf8'
)
ON CONFLICT DO NOTHING;
